# Copyright 2025 CEA LIST - Samir Abou Haidar

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#General Network Config
dataloader:
  batch_size: 2 # 4 for nuScenes and 2 for SemanticKITTI  
  num_workers: 12

augmentations:
  instance_cutmix: False # set True when Training if needed, False when validating (only for SemanticKITTI)

loss:
  lovasz: 1.0

optim:
  lr: 0.001
  weight_decay: 0.003 
  betas: [0.9, 0.999]
  eps: 0.00000001 

scheduler:
  min_lr: 0.00001 
  max_epoch: 90 
  epoch_warmup: 4